name: GitHub Actions pipeline for MicroK8s homelab with OpenTofu
on:
  push:
    branches:
    - main
jobs:
  opentofu-aws:
    runs-on: ubuntu-latest
    steps:
    - name: OpenTofu - Setup Tofu
      uses: opentofu/setup-opentofu@v1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Initialize OpenTofu without backend
      run: |
        tofu -chdir="opentofu/aws/" init -backend=false
    - name: Check OpenTofu formatting
      run: |
        tofu -chdir="opentofu/aws/" fmt -check
    - name: Validate OpenTofu configuration
      run: |
        tofu -chdir="opentofu/aws/" validate
